// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function joinClasses(a, b) {
  return a + (" " + b);
}

function Button$Button(Props) {
  var size = Props.size;
  var color = Props.color;
  var tmp;
  switch (size) {
    case 0 : 
        tmp = "default";
        break;
    case 1 : 
        tmp = "large";
        break;
    case 2 : 
        tmp = "small";
        break;
    
  }
  var tmp$1;
  switch (color) {
    case 0 : 
        tmp$1 = "normal";
        break;
    case 1 : 
        tmp$1 = "primary";
        break;
    case 2 : 
        tmp$1 = "negative";
        break;
    
  }
  return React.jsxs("button", {
              className: joinClasses(tmp, tmp$1)
            });
}

var Button = /* module */[/* make */Button$Button];

function makeProps(param) {
  return (function (param$1) {
      return {
              size: param,
              color: /* Primary */1
            };
    });
}

var RedButton = /* module */[
  /* make */Button$Button,
  /* makeProps */makeProps
];

var foo = React.jsxs(Button$Button, {
      size: /* Default */0,
      color: /* Primary */1
    });

var bar = React.jsxs(Button$Button, {
      size: /* Default */0,
      color: /* Normal */0
    });

exports.joinClasses = joinClasses;
exports.Button = Button;
exports.RedButton = RedButton;
exports.foo = foo;
exports.bar = bar;
/* foo Not a pure module */
