// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Button(Props) {
  var size = Props.size;
  var onClick = Props.onClick;
  var children = Props.children;
  var tmp;
  switch (size) {
    case 0 : 
        tmp = "20px";
        break;
    case 1 : 
        tmp = "30px";
        break;
    case 2 : 
        tmp = "10px";
        break;
    
  }
  return React.jsx("button", {
              children: children,
              style: {
                height: tmp
              },
              onClick: onClick
            });
}

function makeProps(param, param$1, param$2) {
  return {
          size: /* Large */1,
          onClick: param,
          children: param$1
        };
}

var Large = /* module */[
  /* make */Button,
  /* makeProps */makeProps
];

var make = Button;

exports.make = make;
exports.Large = Large;
/* react Not a pure module */
