// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Component1 = require("./Component1.bs.js");
var Component2 = require("./Component2.bs.js");
var ReactDOMRe = require("./vendor/ReactDOMRe.bs.js");

ReactDOMRe.renderToElementWithId(React.jsxs(Component1.make, {
          greeting: "Hello!"
        }), "index1");

ReactDOMRe.renderToElementWithId(React.jsxs(Component2.make, {
          greeting: "Hello!"
        }), "index2");

/*  Not a pure module */
